apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: eexnk32d3-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: eexnk32d3-go 
  name: eexnk32d3-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: eexnk32d3-go 
